version: "3"
tasks:
  generate_proto:
    desc: "Predictor Proto"
    cmds:
      - protoc -I ../matatani-proto
        --go_out=./internal/predictor_service --go_opt=paths=source_relative 
        --go-grpc_out=./internal/predictor_service --go-grpc_opt=paths=source_relative ../matatani-proto/predictor.proto