version: "3"
tasks:
  generate_proto:
    desc: "Build Proto for ML"
    cmds:
      - protoc -I ../matatani-proto
        --go_out=ml --go_opt=paths=source_relative 
        --go-grpc_out=ml --go-grpc_opt=paths=source_relative ../matatani-proto/predictor.proto